from database import engine

try:
    connection = engine.connect()
    print("Conexi√≥n exitosa a la base de datos")
    connection.close()
except Exception as e:
    print("Error al conectar:", e)